spring:
  application:
    name: store-content-manager
  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE_NAME}
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password: 1234
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      database-platform: org.hibernate.dialect.MySQLDialect

db:
  source:
    type: ${DB_SOURCE_TYPE}

fake-store:
  uri: ${STORE_URL}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

server:
  port: 8090
  servlet:
    context-path: /store/management