spring:
  application:
    name: store-content-manager
  security:
    user:
      name: user
      password: password
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE_NAME:store-content-manager-service}
#  datasource:
#    url: jdbc:mysql://localhost:3306/mydb
#    username: root
#    password: 1234
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: true
#      database-platform: org.hibernate.dialect.MySQLDialect

db:
  source:
    type: ${DB_SOURCE_TYPE:mongo}

#mongo
#uri:
#user: tunirch12
#pass: CArLy50npM35vVAC

fake-store:
  uri: ${STORE_URL:https://fakestoreapi.com}

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

server:
  port: 8090
  servlet:
    context-path: /store/management